### ISSUE TITLE
public static func isFirstLaunch(forVersion version: String = "", firstLaunch: FirstLaunch? = nil) -> Bool not correct

### ISSUE THREAD

**Issue by qiusuo8** [tbaranes/VersionTrackerSwift#15]
let isFirstLaunch = VersionTracker.isFirstLaunch(forVersion: "1.0", firstLaunch: nil)
isFirstLaunch always true when app start one more time.

**Comment by tbaranes** [comment]
Just tried out, I'm joining you to say that there's an issue, but I'm getting always false, never fired true 😶
I will take a look at this, thanks for the report!

**Comment by tbaranes** [comment]
I'm currently preparing a 2.0 which should fix that issue, there's a few breaking change, but it's stable. Do you mind give it a try by targeting master once #16 is merged?

The only things left before releasing the 2.0 is adding tests ( #13 ), the README is up to date.

**Comment by tbaranes** [comment]
Should be resolved on master. Will make a release today.
