### ISSUE TITLE
Something happened with the tags

### ISSUE THREAD

**Issue by rudedogg** [tbaranes/VersionTrackerSwift#21]
It looks like the 3.0.0 release wasn't published?

**Comment by tbaranes** [comment]
No, I made a mistake, I tagged 3.0.0 while the next version was 2.0.0 😅 
That's why the 3.0.0 was released but not published, I removed it quickly after.

**Comment by rudedogg** [comment]
Okay that makes sense, I was confused!

**Comment by rudedogg** [comment]
I was looking at the changelog again for changes in #22; there is a 2.0 release for Sep 2017 (https://github.com/tbaranes/VersionTrackerSwift/blob/c973c22d7a2c59258f64a716f54f61b07fb83996/CHANGELOG.md).

Should the most recent release have been 3.0.0? I'm not worried about it, just want to make sure I put the entry for #22 in the right place.

**Comment by tbaranes** [comment]
You are right, seems like the 2.0.0 has never been released. I will fixed this.
Anyway, about #22, you should add an entry in the "next" section

**Comment by tbaranes** [comment]
I fixed the releases' tags:
- 2.0.0 now exists and target the right commit
- 3.0.0 is the latest release

I'm gonna fixed them on pods as well right now. Thanks again for the issue!
