### ISSUE TITLE
Apple's update to their API policy - Required Reason in Privacy manifest

### ISSUE THREAD

**Issue by caosuyang** [tbaranes/VersionTrackerSwift#27]
Add a PrivacyInfo.xcprivacy file and the following information to the Privacy Accessed API Types section

Privacy Accessed API Type: User Defaults

**Comment by tbaranes** [comment]
Thanks for the report. Would you like opening a PR to take care of this?

**Comment by gazadge** [comment]
Hey @tbaranes,
I opened a PR to add the PrivacyInfo file: https://github.com/tbaranes/VersionTrackerSwift/pull/28. Can you take a look when you get a chance?
