### ISSUE TITLE
Publish v3.1.0 spec in CocoaPods/Specs repository

### ISSUE THREAD

**Issue by gazadge** [tbaranes/VersionTrackerSwift#30]
@tbaranes the v3.1.0 release is not yet available via CocoaPods, can you [publish the podspec](https://guides.cocoapods.org/making/getting-setup-with-trunk.html#deploying-a-library)?

**Comment by tbaranes** [comment]
I lost my access to the CocoaPods trunk and not using CocoaPods anymore so I don't think I will do another release there. You should target a tag or a branch directly instead

**Comment by gazadge** [comment]
Okay, no problem. Thank you for your quick response!
