### ISSUE TITLE
Carthage support ?

### ISSUE THREAD

**Issue by El-Fitz** [tbaranes/VersionTrackerSwift#9]
Carthage is awesome 😊
(I just hate Cocoapods. I don't know how much work it would require though)

**Comment by tbaranes** [comment]
Since I'm not a Carthage user,  I won't add it myself, but feel free to send a PR for this feature! 🙃

**Comment by El-Fitz** [comment]
Well... I'm just more or less starting in swift.
But as soon as I can, I will ! Might take some time though 🙂

**Comment by tbaranes** [comment]
@El-Fitz Just read some documentation on Carthage, I think `VersionTrackerSwift` is already compatible even if it's not explicitly said in the README. Did you try? Which errors did you get?

**Comment by El-Fitz** [comment]
I'm going to look into it asap

**Comment by El-Fitz** [comment]
So, looked into it, and...

Tadaaa ! My first pull request ever ! 😊 #11 
"All" it takes is to remove the SwitLint run scripts, because not everyone has SwiftLint. Do you need to leave the it in the release versions ?

update: So, this is better #12
